In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('aug_train.csv')

# 1. How big is the data?

In [4]:
df.shape

(19158, 14)

# 2. How does the data look like?

In [5]:
df.sample(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
15219,16748,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,50-99,Pvt Ltd,1,77,0.0
16179,24854,city_70,0.698,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,10000+,Pvt Ltd,1,11,0.0
5145,22015,city_160,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,>4,36,0.0
12198,19432,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,16,10000+,Pvt Ltd,>4,21,1.0
2209,26169,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,100-500,Pvt Ltd,1,50,1.0

# 3. What is the data type of cols?

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 2.0 MB

# 4. Are there any missing values?

In [7]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

# 5. How does the data look mathematically?

In [8]:
df.describe()

        enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

# 6. Are there duplicate values?

In [11]:
df.duplicated().sum()

np.int64(0)

# 7. How is the correlation between cols?

In [16]:
df.corr(numeric_only=True)['city_development_index']

enrollee_id              -0.040455
city_development_index    1.000000
training_hours            0.001920
target                   -0.341665
Name: city_development_index, dtype: float64